### PR TITLE
#933 Added `isPullRequest` flag for a `Task` to be stored.

### LINKED ISSUE #933: Save the PR flag on the Task
When registering a task, we should also save the flag ``isPullRequest`` (true || false). We need this in order to solve #932 completely, and we will also need it when we will want to use the ``E-Tag`` mechanism in order to avoid useless API calls.

### PR DESCRIPTION
**Pull request by criske**
Closes #933

### CODE REVIEW

**Comment by charlesmike** [comment]
@criske thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by criske** [comment]
no bounty

**Comment by charlesmike** [comment]
@amihaiemil please review this Pull Request. Deadline (when it should be merged or closed) is ``2021-01-29T14:54:01.986992``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by amihaiemil** [comment]
@criske Yes, I think we should also add isPullRequest to equals/hashcode. 

Otherwise, it looks good!

**Comment by criske** [comment]
@amihaiemil done :D

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
