### PR TITLE
#778 Fixed bug where GitlaIssues#getById returned GithubIssue.

### LINKED ISSUE #778: Bug in GitlabIssues.getById(); GithubIssue.java is used instead of GitlabIssue.java
@amihaiemil @criske There is bug in the implementation of `GitlabIssues.getById()` method, where `GithubIssue` is used instead of `GitlabIssue` instance. 

https://github.com/self-xdsd/self-core/blob/6852fc54eec416de08f733482edee6942a30ec81/self-core-impl/src/main/java/com/selfxdsd/core/GitlabIssues.java#L113-L119

### PR DESCRIPTION
**Pull request by criske**
fixes #778

### CODE REVIEW

**Comment by charlesmike** [comment]
@criske thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by criske** [comment]
@amihaiemil no bounty, sorry again for the bug :D

**Comment by charlesmike** [comment]
@amihaiemil please review this Pull Request. Deadline (when it should be merged or closed) is ``2020-12-11T19:35:49.493177``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by charlesmike** [comment]
@amihaiemil Don't forget to close this ticket before the deadline (2020-12-11T19:35:49). You are past the first half of the allowed period.

**Comment by amihaiemil** [comment]
@criske no problem, thanks!

**Comment by amihaiemil** [comment]
@rultor merge it please

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
