### PR TITLE
#670 Customer name, description and email

### LINKED ISSUE #670: Send Project name and Description on Stripe Wallet Setup
When we create a Project's Stripe Wallet, we should send the project name and description to Stripe, otherwise the Customers Table will be empty on the Stripe Dashboard:

Screenshot 2020-11-06 at 21 19 01

### PR DESCRIPTION
**Pull request by amihaiemil**
Fixes #670

### CODE REVIEW

**Comment by charlesmike** [comment]
@amihaiemil thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by charlesmike** [comment]
@amihaiemil please review this Pull Request. Deadline (when it should be merged or closed) is ``2020-11-10T11:08:59.335407``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
