### PR TITLE
#826 Invoice.toPdf() implemented

### LINKED ISSUE #826: Invoice as PDF
We should have method Invoice.toPdf() to turn it into a PDF File.

### PR DESCRIPTION
**Pull request by amihaiemil**
Fixes #826 

We use a PDF AcroForm template and Apache PdfBox to fill it out with the Invoice's data.
Invoice.toPdf() returns a ``File`` representing the created PDF on disk.
Left puzzle to write multiple pages if there are more than 40 tasks.

### CODE REVIEW

**Comment by charlesmike** [comment]
@amihaiemil thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by charlesmike** [comment]
@amihaiemil please review this Pull Request. Deadline (when it should be merged or closed) is ``2020-12-27T22:03:42.883892``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by amihaiemil** [comment]
@rultor merge

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
