### PR TITLE
#1013 Start implementing BitbucketRepo::issues()

### PR DESCRIPTION
**Pull request by fellahi-ali**
PR for #1013
I think this PR is relatively big :( , because I found myself required to fill some gaps to keep the code consistent :)

### CODE REVIEW

**Comment by zoeself** [comment]
@fellahi-ali thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by zoeself** [comment]
@amihaiemil I couldn't find any assignee for this task. This is either because there are no contributors with role ``REV`` available or because the project does not have enough funds.

Please, make sure there is at least one available contributor with the required role and the project can afford to pay them.

**Comment by amihaiemil** [comment]
@fellahi-ali looks good! 

Actually, I don't know how Bitbucket Issues will work. From what I see, there are no Issues in BitBucket... instead, you can have issues/tickets in BitBucket if you integrate Jira. (cc: @criske). 

So I'm not sure how BitBucketIssues will be implemented. But anyway, it's a good start, thanks!

**Comment by criske** [comment]
@amihaiemil @fellahi-ali Jira issues not supported by Bitbucket API, at least for now. PO must activate the local issue tracker from "Repository Settings"  in order that Issues api to work.

issues


Otherwise we will get.
```json
{
    "type": "error",
    "error": {
        "message": "Repository has no issue tracker."
    }
}
```
Maybe we should throw ISE, when get this message instead of returning null on `Issues#getById`.
Also the exception message may instruct user on how to activate the issue tracker and warn that Jira is not supported.

**Comment by fellahi-ali** [comment]
Thanks @criske for insights, I was actually struggling to use the issues API, but couldn't, I  only used/trusted the available doc to impl this task, and I don't know if we could go further?

**Pull request merged**
