### PR TITLE
#689 add or remove contributor label

### LINKED ISSUE #689: Add/Remove Contributor Label
When assigning/unassigning an Issue, we should add/remove a Label with the contributor's tag (e.g. ``@amihaiemil``).

### PR DESCRIPTION
**Pull request by amihaiemil**
Fixes #689 

* Added and tested WithContributorLabel issue decorator
* Contributor tag (e.g. ``@amihaiemil``) is now added/removed when the issue is assigned/unassigned
* Left puzzle for GithubRepoLabels.

### CODE REVIEW

**Comment by charlesmike** [comment]
@amihaiemil thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by amihaiemil** [comment]
@rultor merge it please

**Comment by charlesmike** [comment]
@amihaiemil please review this Pull Request. Deadline (when it should be merged or closed) is ``2020-11-15T12:17:20.925155``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
