### PR TITLE
#667 RestfulSelfTodos implemented and tested

### LINKED ISSUE #667: Implement SelfTodos
Similarly to how Github is implemented (using JsonResources), we should implement SelfTodos, so we can forward the push event to the self-todos microservice.

### PR DESCRIPTION
**Pull request by amihaiemil**
Fixes #667

### CODE REVIEW

**Comment by charlesmike** [comment]
@amihaiemil thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by amihaiemil** [comment]
@rultor merge it please

**Comment by charlesmike** [comment]
@criske please review this Pull Request. Deadline (when it should be merged or closed) is ``2020-11-09T21:08:59.284487``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by amihaiemil** [comment]
@rultor merge

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
