### PR TITLE
#917 UserProjects.getProjectById() searches in Storage directly

### LINKED ISSUE #917: UserProjects.getProjectById Should Select From Storage
At the moment this method iterates over the encapsulated Projects Stream (which will select all the user's projects). This is inefficient. 

Instead, this method should first check if the queried project belongs to the User and if so, return it directly from the Storage (this will prevent having to iterate over all the user's projects).

### PR DESCRIPTION
**Pull request by amihaiemil**
Fixes #917 

* Both UserProjects and PmProjects now encapsulate the Storage
* UserProjects.getProjectById() searches in the storage directly
* updated unit tests

### CODE REVIEW

**Comment by charlesmike** [comment]
@amihaiemil thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by amihaiemil** [comment]
@rultor merge it please

**Comment by charlesmike** [comment]
@amihaiemil please review this Pull Request. Deadline (when it should be merged or closed) is ``2021-01-23T10:06:13.742929``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
