### PR TITLE
#711 Manager Commission as Percentage

### LINKED ISSUE #711: Self's Commission Should Be Percentage of Payment
At the moment we have a fixed commission (e.g. 1 EUR/invoiced task). However, this will not work because of Stripe's fees which are calculated differently from what we initially thought.

In order to make sure Self is not losing money, its commission should be a percentage from the Invoice's value.
In other words, a percentage from each payment being made. Minimum viable commission is 5%.

### PR DESCRIPTION
**Pull request by amihaiemil**
Fixes #711 

* StoredProjectManager takes commission as ``double``
* Method ProjectManager.percentage() to return the double percentage
* Method BigDecimal::ProjectManager.commission(...) to calculate the effective commission for a value
* Updated dependent code
* Updated tests (and added test for the new ``commission(...)`` method).

* Updated ProjectManagers.register(...) to accept the commission as double percentage.

### CODE REVIEW

**Comment by charlesmike** [comment]
@amihaiemil thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by charlesmike** [comment]
@amihaiemil please review this Pull Request. Deadline (when it should be merged or closed) is ``2020-11-26T14:21:51.624307``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by amihaiemil** [comment]
@rultor merge

**Comment by amihaiemil** [comment]
@rultor try to merge again

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
