### PR TITLE
#691 GithubRepoLabels implemented and tested

### PR DESCRIPTION
**Pull request by amihaiemil**
PR for #691 

Implemented and tested GithubRepoLabels;
Implemented and tested Repo.labels();
Added puzzle to use GithubRepoLabels inside GithubIssueLabels.add(...) in order to register the repo with a random color;

### CODE REVIEW

**Comment by charlesmike** [comment]
@amihaiemil thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by charlesmike** [comment]
@amihaiemil please review this Pull Request. Deadline (when it should be merged or closed) is ``2020-11-15T15:17:21.895144``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by amihaiemil** [comment]
@rultor merge it please

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
