### PR TITLE
#673: Remove method Commits#received

### PR DESCRIPTION
**Pull request by andreoss**
Per #673 
- Remove method and its usage

### CODE REVIEW

**Comment by charlesmike** [comment]
@andreoss thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by charlesmike** [comment]
@criske please review this Pull Request. Deadline (when it should be merged or closed) is ``2020-11-12T22:37:22.808854``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Review by criske — APPROVED** [review]
@andreoss looks good

**Comment by amihaiemil** [comment]
@rultor merge it please

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
