### PR TITLE
#819 BillingInfo for individual or company and taxId

### LINKED ISSUE #819: BillingInfo: add individual/company and taxId
BillingInfo should hold the full name if it's an individual or the company name if it's a business.
It should also hold the taxId (VAT number identifier) in either case.

### PR DESCRIPTION
**Pull request by amihaiemil**
Fixes #819 

BillingInfo now has the isCompany flag;
If isCompany then it should have a legalName;
if !isCompany then it should have firstName + lastName;
Added taxId attribute.

### CODE REVIEW

**Comment by charlesmike** [comment]
@amihaiemil thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by charlesmike** [comment]
@amihaiemil please review this Pull Request. Deadline (when it should be merged or closed) is ``2020-12-25T16:24:15.752977``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by amihaiemil** [comment]
@rultor merge it please

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
