### PR TITLE
#599 Implementend and tested Wallet#updateCash().

### PR DESCRIPTION
**Pull request by criske**
PR for #599

### CODE REVIEW

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by amihaiemil** [comment]
@criske Can you please have a look here? There were some merge conflicts which I tried to solve from Github UI, but now Travis complains with a compilation error that I cannot solve...

**Comment by criske** [comment]
@amihaiemil I think is fixed now :D

**Comment by amihaiemil** [comment]
@rultor merge it please

**Comment by amihaiemil** [comment]
@criske thanks!

**Pull request merged**
