### PR TITLE
#1178 Fixed compilation error.

### PR DESCRIPTION
**Pull request by criske**
PR for #1178

### CODE REVIEW

**Comment by zoeself** [comment]
@criske thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by criske** [comment]
@amihaiemil Sorry about, I had at one point a mental note to update the last PR with master after #1174 was merged and I completly forgot to do it.

**Comment by zoeself** [comment]
@amihaiemil I couldn't find any assignee for this task. This is either because there are no contributors with role ``REV`` available or because the project does not have enough funds.

Please, make sure there is at least one available contributor with the required role and the project can afford to pay them.

**Comment by amihaiemil** [comment]
@criske no stress :D

**Pull request merged**
