### PR TITLE
#707 'Hello' Issue after Accepting Invitation

### LINKED ISSUE #707: Open Issue on Accepted Invitation
When the PM accepts a Repo Invitation, it should open a ``no-task`` Issue, saying "hello" and introducing itself, saying everything is porperly set up.

### PR DESCRIPTION
**Pull request by amihaiemil**
Fixes #707 

Implemented and tested GithubInvitation.repo();
Pulled out and tested StarRepo decorator for an Invitation;
Implemented and tested HelloIssue decorator for an Invitation;

Used the 2 decorators over GithubInvitation (GithubInvitations.iterator());

### CODE REVIEW

**Comment by charlesmike** [comment]
@amihaiemil thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by amihaiemil** [comment]
@rultor merge

**Comment by charlesmike** [comment]
@amihaiemil please review this Pull Request. Deadline (when it should be merged or closed) is ``2020-11-22T11:41:50.438547``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
