### PR TITLE
#676 reply to new/reopened ticket only if author != self

### LINKED ISSUE #676: Don't Reply If Issue/PR Author is Self
On new_issue or reopened_issue events, do not reply if the issue or PR author is the PM itself.

### PR DESCRIPTION
**Pull request by amihaiemil**
Fixes #676 
If the PM is the author of a new or reopened ticket, it should not reply to itself.

### CODE REVIEW

**Comment by charlesmike** [comment]
@amihaiemil thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by amihaiemil** [comment]
@rultor merge it please

**Comment by charlesmike** [comment]
@amihaiemil please review this Pull Request. Deadline (when it should be merged or closed) is ``2020-11-12T14:57:23.055998``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
