### PR TITLE
#550. ProviderContributors implemented+tested.

### PR DESCRIPTION
**Pull request by criske**
PR for #550

### CODE REVIEW

**Comment by criske** [comment]
@amihaiemil I've noticing something odd. Why do we add a 0 hourly rate `Contract` in `ProjectContributors#register`?
https://github.com/self-xdsd/self-core/blob/a27f1cd4cafd99bb154194f916e4f3f764406ace/self-core-impl/src/main/java/com/selfxdsd/core/contributors/ProjectContributors.java#L130

**Comment by amihaiemil** [comment]
@criske 
> Why do we add a 0 hourly rate Contract in ProjectContributors#register

We first register him as a Contributor and then we have to register a Contract with the Project, otherwise he will not be a project contributor. We just assume the default role to be ``DEV`` and default hourly rate to be ``0``.

We will change this, most likely. I want to have a minimum hourly rate, say ``$10/h`` in any project and any role.

**Comment by amihaiemil** [comment]
@criske the PR looks good, but it's a little too big...

**Comment by amihaiemil** [comment]
@rultor merge it please

**Pull request merged**
