### PR TITLE
#775 GitlabIssues.received() impl & test

### PR DESCRIPTION
**Pull request by fellahi-ali**
RP for #775

### CODE REVIEW

**Comment by charlesmike** [comment]
@fellahi-ali thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by charlesmike** [comment]
@amihaiemil please review this Pull Request. Deadline (when it should be merged or closed) is ``2020-12-12T01:25:50.044707``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by fellahi-ali** [comment]
@amihaiemil If I'm not missing something, I think this task is over estimated, and I should be payed for just 30min instead of  60min.

**Comment by fellahi-ali** [comment]
@amihaiemil Travis build failed because of some integration test, but I run the build locally and it passes; I don't know how to fix this?

**Comment by amihaiemil** [comment]
@fellahi-ali all tasks have 60min estimation. If you manage to do it faster, it's your win :) 

Don't worry about Travis, sometimes those integration tests fail because Github blocks our calls, for some reason...

**Comment by amihaiemil** [comment]
@rultor merge it please

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
