### PR TITLE
Added register() method in ProjectManagers

### PR DESCRIPTION
**Pull request by criske**
PR for #86 

Implemented InMemoryProjectManagers#register()

Note: named the method `register`, instead of `addProjectManager`, to mantain the naming convention used in Projects.

### CODE REVIEW

**Comment by amihaiemil** [comment]
@criske arata ok. As vrea sa asteptam dupa #88 -- el a adaugat primul fisierul ``InMemoryProjectManagersTestCase`` si deja s-a lovit o data de merge conflicts.

Dupa aceea, poti lua fisierul lui si sa adaugi in el testele tale.

**Comment by criske** [comment]
Ok

**Comment by amihaiemil** [comment]
@criske #88 has been merged :D

**Comment by amihaiemil** [comment]
@criske there are still some conflicts :( I think some indentation changes :D

**Comment by amihaiemil** [comment]
@rultor merge it

**Pull request merged**
