### PR TITLE
Commits#latest is now nullable.

### PR DESCRIPTION
**Pull request by criske**
Otherwise will throw index out of bounds exception if there are no commits

--
no bounty needed

### CODE REVIEW

**Comment by charlesmike** [comment]
@criske thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by criske** [comment]
@amihaiemil Anyway I've tested most of the gitlab features against a real repo. Only thing I've missed testing is processing webhook responses.
I hope from now on there won't problems with gitlab on front end anymore :D

**Comment by charlesmike** [comment]
@amihaiemil please review this Pull Request. Deadline (when it should be merged or closed) is ``2021-01-22T14:16:15.364739``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by amihaiemil** [comment]
@criske This won't be necessary. We use the Commits API only on ``PUSH`` events received from Github or GitLab. 
If we have a PUSH event, it's clear that we already have at least one commit in the Repo. 

And if we make Commit.latest() nullable, then we also need to change the client code (code calling Commit.latest()) and add ``if null else`` statements... 

I would rather leave it as it is with no changes.

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request closed without merging**
