### PR TITLE
#793 equalsIgnoreCase repoFullName, provider, username everywhere

### LINKED ISSUE #793: Elected Contributor Doesn't Have Contract
We have this in the logs:

```java
2020-12-14 11:16:54.034 DEBUG 2224 --- [scheduling-1] c.selfxdsd.selfpm.ReviewUnassignedTasks  : Reviewing unassigned tasks from project Dejeu-Org/Repo1 at github... 
2020-12-14 11:16:54.036 DEBUG 2224 --- [scheduling-1] c.s.core.managers.StoredProjectManager   : Checking the unassigned tasks of project Dejeu-Org/Repo1 at github
2020-12-14 11:16:54.585 DEBUG 2224 --- [scheduling-1] c.s.core.managers.StoredProjectManager   : Elected @MihaiDejeu.
2020-12-14 11:16:54.603 ERROR 2224 --- [scheduling-1] c.selfxdsd.selfpm.ReviewUnassignedTasks  : Problem while reviewing unassigned tasks of Project Dejeu-Org/Repo1 at github

com.selfxdsd.api.exceptions.TasksException$Single$Assign: Task [2] The given contributor doesn't have the needed contract!
	at com.selfxdsd.core.tasks.StoredTask.assign(StoredTask.java:176) ~[self-core-impl-0.0.42.jar!/:na]
	at com.selfxdsd.core.managers.StoredProjectManager.assignTask(StoredProjectManager.java:421) ~[self-core-impl-0.0.42.jar!/:na]
	at com.selfxdsd.core.managers.StoredProjectManager.unassignedTasks(StoredProjectManager.java:383) ~[self-core-impl-0.0.42.jar!/:na]
	at com.selfxdsd.core.projects.StoredProject.resolve(StoredProject.java:185) ~[self-core-impl-0.0.42.jar!/:na]
	at com.selfxdsd.selfpm.ReviewUnassignedTasks.reviewUnassignedTasks(ReviewUnassignedTasks.java:87) ~[classes!/:0.0.4-SNAPSHOT]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

It's a bug, this should never happen. Let's fix it.

### PR DESCRIPTION
**Pull request by amihaiemil**
Fixes #793 

The problem was about equals comparison in Contract id, which should have been equalsIgnoreCase.
For safety reasons, we changed all the equals for username, repoFullName and provider to equalsIgnoreCase.

### CODE REVIEW

**Comment by charlesmike** [comment]
@amihaiemil thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by amihaiemil** [comment]
@rultor merge it please

**Comment by charlesmike** [comment]
@amihaiemil please review this Pull Request. Deadline (when it should be merged or closed) is ``2020-12-17T14:10:36.315579``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
